# Generated by Django 5.2.8 on 2025-11-25 18:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assets', '0001_initial'),
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assetsparepartlink',
            name='part',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.part'),
        ),
    ]
