# Generated by Django 5.2.8 on 2025-11-25 18:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
        ('locations', '0001_initial'),
        ('plants', '0001_initial'),
        ('work_orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='parttransaction',
            name='work_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='work_orders.workorder'),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='locations.location'),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='plant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plants.plant'),
        ),
        migrations.AddField(
            model_name='parttransaction',
            name='warehouse_from',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions_out', to='inventory.warehouse'),
        ),
        migrations.AddField(
            model_name='parttransaction',
            name='warehouse_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions_in', to='inventory.warehouse'),
        ),
        migrations.AddField(
            model_name='partstock',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.warehouse'),
        ),
        migrations.AlterUniqueTogether(
            name='partstock',
            unique_together={('part', 'warehouse', 'condition')},
        ),
    ]
