# Generated by Django 5.2.8 on 2025-11-25 18:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assets', '0002_initial'),
        ('plants', '0001_initial'),
        ('work_orders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChecklistItemTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ChecklistExecution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('performed_at', models.DateTimeField(auto_now_add=True)),
                ('overall_status', models.CharField(choices=[('OK', 'OK'), ('NOT_OK', 'Not OK'), ('PARTIAL', 'Partial')], max_length=20)),
                ('performed_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('work_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklist_executions', to='work_orders.workorder')),
            ],
        ),
        migrations.CreateModel(
            name='ChecklistItemExecution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_ok', models.BooleanField(null=True)),
                ('comment', models.TextField(blank=True)),
                ('execution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_executions', to='maintenance.checklistexecution')),
                ('template_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maintenance.checklistitemtemplate')),
            ],
        ),
        migrations.CreateModel(
            name='ChecklistTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='assets.asset')),
                ('asset_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='assets.assetcategory')),
                ('plant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plants.plant')),
            ],
        ),
        migrations.AddField(
            model_name='checklistitemtemplate',
            name='checklist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='maintenance.checklisttemplate'),
        ),
        migrations.AddField(
            model_name='checklistexecution',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maintenance.checklisttemplate'),
        ),
        migrations.CreateModel(
            name='PMTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('frequency_type', models.CharField(choices=[('DAY_BASED', 'Day Based'), ('RUNTIME_BASED', 'Runtime Based')], max_length=20)),
                ('interval_days', models.IntegerField(blank=True, null=True)),
                ('interval_hours', models.IntegerField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='assets.asset')),
                ('asset_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='assets.assetcategory')),
                ('plant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plants.plant')),
            ],
        ),
        migrations.CreateModel(
            name='PMSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('next_due_date', models.DateField(blank=True, null=True)),
                ('last_done_date', models.DateField(blank=True, null=True)),
                ('last_done_hours', models.IntegerField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assets.asset')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maintenance.pmtemplate')),
            ],
        ),
    ]
